version: 2.1

workflows:
  test-env-var:
    jobs:
      - build

jobs:
  build:
    docker:
      - image:  cimg/node:13.8.0
    
    steps:
      - checkout
      - run:
          name: "echo an env that is part of project"
          command: |
            echo $MY_ENV_VAR